/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as OrderRouteImport } from './routes/order'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppZonesRouteImport } from './routes/app.zones'
import { Route as AppWarehousesRouteImport } from './routes/app.warehouses'
import { Route as AppUsersRouteImport } from './routes/app.users'
import { Route as AppSuppliersRouteImport } from './routes/app.suppliers'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppSellersRouteImport } from './routes/app.sellers'
import { Route as AppSalesRouteImport } from './routes/app.sales'
import { Route as AppReportsRouteImport } from './routes/app.reports'
import { Route as AppReceivablesRouteImport } from './routes/app.receivables'
import { Route as AppProductsRouteImport } from './routes/app.products'
import { Route as AppProductionRouteImport } from './routes/app.production'
import { Route as AppPayablesRouteImport } from './routes/app.payables'
import { Route as AppOrdersRouteImport } from './routes/app.orders'
import { Route as AppMovementsRouteImport } from './routes/app.movements'
import { Route as AppLogisticsRouteImport } from './routes/app.logistics'
import { Route as AppInvoicesRouteImport } from './routes/app.invoices'
import { Route as AppInventoryRouteImport } from './routes/app.inventory'
import { Route as AppCustomersRouteImport } from './routes/app.customers'
import { Route as AppCashboxRouteImport } from './routes/app.cashbox'
import { Route as AppAuditRouteImport } from './routes/app.audit'
import { Route as AppAnalyticsRouteImport } from './routes/app.analytics'
import { Route as ApiPublicBootstrapAdminRouteImport } from './routes/api/public/bootstrap-admin'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderRoute = OrderRouteImport.update({
  id: '/order',
  path: '/order',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppZonesRoute = AppZonesRouteImport.update({
  id: '/zones',
  path: '/zones',
  getParentRoute: () => AppRoute,
} as any)
const AppWarehousesRoute = AppWarehousesRouteImport.update({
  id: '/warehouses',
  path: '/warehouses',
  getParentRoute: () => AppRoute,
} as any)
const AppUsersRoute = AppUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppRoute,
} as any)
const AppSuppliersRoute = AppSuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppSellersRoute = AppSellersRouteImport.update({
  id: '/sellers',
  path: '/sellers',
  getParentRoute: () => AppRoute,
} as any)
const AppSalesRoute = AppSalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppReceivablesRoute = AppReceivablesRouteImport.update({
  id: '/receivables',
  path: '/receivables',
  getParentRoute: () => AppRoute,
} as any)
const AppProductsRoute = AppProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AppRoute,
} as any)
const AppProductionRoute = AppProductionRouteImport.update({
  id: '/production',
  path: '/production',
  getParentRoute: () => AppRoute,
} as any)
const AppPayablesRoute = AppPayablesRouteImport.update({
  id: '/payables',
  path: '/payables',
  getParentRoute: () => AppRoute,
} as any)
const AppOrdersRoute = AppOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AppRoute,
} as any)
const AppMovementsRoute = AppMovementsRouteImport.update({
  id: '/movements',
  path: '/movements',
  getParentRoute: () => AppRoute,
} as any)
const AppLogisticsRoute = AppLogisticsRouteImport.update({
  id: '/logistics',
  path: '/logistics',
  getParentRoute: () => AppRoute,
} as any)
const AppInvoicesRoute = AppInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => AppRoute,
} as any)
const AppInventoryRoute = AppInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AppRoute,
} as any)
const AppCustomersRoute = AppCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AppRoute,
} as any)
const AppCashboxRoute = AppCashboxRouteImport.update({
  id: '/cashbox',
  path: '/cashbox',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditRoute = AppAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const ApiPublicBootstrapAdminRoute = ApiPublicBootstrapAdminRouteImport.update({
  id: '/api/public/bootstrap-admin',
  path: '/api/public/bootstrap-admin',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/order': typeof OrderRoute
  '/portal': typeof PortalRoute
  '/signup': typeof SignupRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/audit': typeof AppAuditRoute
  '/app/cashbox': typeof AppCashboxRoute
  '/app/customers': typeof AppCustomersRoute
  '/app/inventory': typeof AppInventoryRoute
  '/app/invoices': typeof AppInvoicesRoute
  '/app/logistics': typeof AppLogisticsRoute
  '/app/movements': typeof AppMovementsRoute
  '/app/orders': typeof AppOrdersRoute
  '/app/payables': typeof AppPayablesRoute
  '/app/production': typeof AppProductionRoute
  '/app/products': typeof AppProductsRoute
  '/app/receivables': typeof AppReceivablesRoute
  '/app/reports': typeof AppReportsRoute
  '/app/sales': typeof AppSalesRoute
  '/app/sellers': typeof AppSellersRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/suppliers': typeof AppSuppliersRoute
  '/app/users': typeof AppUsersRoute
  '/app/warehouses': typeof AppWarehousesRoute
  '/app/zones': typeof AppZonesRoute
  '/app/': typeof AppIndexRoute
  '/api/public/bootstrap-admin': typeof ApiPublicBootstrapAdminRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/order': typeof OrderRoute
  '/portal': typeof PortalRoute
  '/signup': typeof SignupRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/audit': typeof AppAuditRoute
  '/app/cashbox': typeof AppCashboxRoute
  '/app/customers': typeof AppCustomersRoute
  '/app/inventory': typeof AppInventoryRoute
  '/app/invoices': typeof AppInvoicesRoute
  '/app/logistics': typeof AppLogisticsRoute
  '/app/movements': typeof AppMovementsRoute
  '/app/orders': typeof AppOrdersRoute
  '/app/payables': typeof AppPayablesRoute
  '/app/production': typeof AppProductionRoute
  '/app/products': typeof AppProductsRoute
  '/app/receivables': typeof AppReceivablesRoute
  '/app/reports': typeof AppReportsRoute
  '/app/sales': typeof AppSalesRoute
  '/app/sellers': typeof AppSellersRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/suppliers': typeof AppSuppliersRoute
  '/app/users': typeof AppUsersRoute
  '/app/warehouses': typeof AppWarehousesRoute
  '/app/zones': typeof AppZonesRoute
  '/app': typeof AppIndexRoute
  '/api/public/bootstrap-admin': typeof ApiPublicBootstrapAdminRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/order': typeof OrderRoute
  '/portal': typeof PortalRoute
  '/signup': typeof SignupRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/audit': typeof AppAuditRoute
  '/app/cashbox': typeof AppCashboxRoute
  '/app/customers': typeof AppCustomersRoute
  '/app/inventory': typeof AppInventoryRoute
  '/app/invoices': typeof AppInvoicesRoute
  '/app/logistics': typeof AppLogisticsRoute
  '/app/movements': typeof AppMovementsRoute
  '/app/orders': typeof AppOrdersRoute
  '/app/payables': typeof AppPayablesRoute
  '/app/production': typeof AppProductionRoute
  '/app/products': typeof AppProductsRoute
  '/app/receivables': typeof AppReceivablesRoute
  '/app/reports': typeof AppReportsRoute
  '/app/sales': typeof AppSalesRoute
  '/app/sellers': typeof AppSellersRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/suppliers': typeof AppSuppliersRoute
  '/app/users': typeof AppUsersRoute
  '/app/warehouses': typeof AppWarehousesRoute
  '/app/zones': typeof AppZonesRoute
  '/app/': typeof AppIndexRoute
  '/api/public/bootstrap-admin': typeof ApiPublicBootstrapAdminRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/order'
    | '/portal'
    | '/signup'
    | '/app/analytics'
    | '/app/audit'
    | '/app/cashbox'
    | '/app/customers'
    | '/app/inventory'
    | '/app/invoices'
    | '/app/logistics'
    | '/app/movements'
    | '/app/orders'
    | '/app/payables'
    | '/app/production'
    | '/app/products'
    | '/app/receivables'
    | '/app/reports'
    | '/app/sales'
    | '/app/sellers'
    | '/app/settings'
    | '/app/suppliers'
    | '/app/users'
    | '/app/warehouses'
    | '/app/zones'
    | '/app/'
    | '/api/public/bootstrap-admin'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/order'
    | '/portal'
    | '/signup'
    | '/app/analytics'
    | '/app/audit'
    | '/app/cashbox'
    | '/app/customers'
    | '/app/inventory'
    | '/app/invoices'
    | '/app/logistics'
    | '/app/movements'
    | '/app/orders'
    | '/app/payables'
    | '/app/production'
    | '/app/products'
    | '/app/receivables'
    | '/app/reports'
    | '/app/sales'
    | '/app/sellers'
    | '/app/settings'
    | '/app/suppliers'
    | '/app/users'
    | '/app/warehouses'
    | '/app/zones'
    | '/app'
    | '/api/public/bootstrap-admin'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/order'
    | '/portal'
    | '/signup'
    | '/app/analytics'
    | '/app/audit'
    | '/app/cashbox'
    | '/app/customers'
    | '/app/inventory'
    | '/app/invoices'
    | '/app/logistics'
    | '/app/movements'
    | '/app/orders'
    | '/app/payables'
    | '/app/production'
    | '/app/products'
    | '/app/receivables'
    | '/app/reports'
    | '/app/sales'
    | '/app/sellers'
    | '/app/settings'
    | '/app/suppliers'
    | '/app/users'
    | '/app/warehouses'
    | '/app/zones'
    | '/app/'
    | '/api/public/bootstrap-admin'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  OrderRoute: typeof OrderRoute
  PortalRoute: typeof PortalRoute
  SignupRoute: typeof SignupRoute
  ApiPublicBootstrapAdminRoute: typeof ApiPublicBootstrapAdminRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order': {
      id: '/order'
      path: '/order'
      fullPath: '/order'
      preLoaderRoute: typeof OrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/zones': {
      id: '/app/zones'
      path: '/zones'
      fullPath: '/app/zones'
      preLoaderRoute: typeof AppZonesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/warehouses': {
      id: '/app/warehouses'
      path: '/warehouses'
      fullPath: '/app/warehouses'
      preLoaderRoute: typeof AppWarehousesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/users': {
      id: '/app/users'
      path: '/users'
      fullPath: '/app/users'
      preLoaderRoute: typeof AppUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/suppliers': {
      id: '/app/suppliers'
      path: '/suppliers'
      fullPath: '/app/suppliers'
      preLoaderRoute: typeof AppSuppliersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/sellers': {
      id: '/app/sellers'
      path: '/sellers'
      fullPath: '/app/sellers'
      preLoaderRoute: typeof AppSellersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/sales': {
      id: '/app/sales'
      path: '/sales'
      fullPath: '/app/sales'
      preLoaderRoute: typeof AppSalesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reports': {
      id: '/app/reports'
      path: '/reports'
      fullPath: '/app/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/receivables': {
      id: '/app/receivables'
      path: '/receivables'
      fullPath: '/app/receivables'
      preLoaderRoute: typeof AppReceivablesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/products': {
      id: '/app/products'
      path: '/products'
      fullPath: '/app/products'
      preLoaderRoute: typeof AppProductsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/production': {
      id: '/app/production'
      path: '/production'
      fullPath: '/app/production'
      preLoaderRoute: typeof AppProductionRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/payables': {
      id: '/app/payables'
      path: '/payables'
      fullPath: '/app/payables'
      preLoaderRoute: typeof AppPayablesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/orders': {
      id: '/app/orders'
      path: '/orders'
      fullPath: '/app/orders'
      preLoaderRoute: typeof AppOrdersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/movements': {
      id: '/app/movements'
      path: '/movements'
      fullPath: '/app/movements'
      preLoaderRoute: typeof AppMovementsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/logistics': {
      id: '/app/logistics'
      path: '/logistics'
      fullPath: '/app/logistics'
      preLoaderRoute: typeof AppLogisticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/invoices': {
      id: '/app/invoices'
      path: '/invoices'
      fullPath: '/app/invoices'
      preLoaderRoute: typeof AppInvoicesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/inventory': {
      id: '/app/inventory'
      path: '/inventory'
      fullPath: '/app/inventory'
      preLoaderRoute: typeof AppInventoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/customers': {
      id: '/app/customers'
      path: '/customers'
      fullPath: '/app/customers'
      preLoaderRoute: typeof AppCustomersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/cashbox': {
      id: '/app/cashbox'
      path: '/cashbox'
      fullPath: '/app/cashbox'
      preLoaderRoute: typeof AppCashboxRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/audit': {
      id: '/app/audit'
      path: '/audit'
      fullPath: '/app/audit'
      preLoaderRoute: typeof AppAuditRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/analytics': {
      id: '/app/analytics'
      path: '/analytics'
      fullPath: '/app/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/public/bootstrap-admin': {
      id: '/api/public/bootstrap-admin'
      path: '/api/public/bootstrap-admin'
      fullPath: '/api/public/bootstrap-admin'
      preLoaderRoute: typeof ApiPublicBootstrapAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppAuditRoute: typeof AppAuditRoute
  AppCashboxRoute: typeof AppCashboxRoute
  AppCustomersRoute: typeof AppCustomersRoute
  AppInventoryRoute: typeof AppInventoryRoute
  AppInvoicesRoute: typeof AppInvoicesRoute
  AppLogisticsRoute: typeof AppLogisticsRoute
  AppMovementsRoute: typeof AppMovementsRoute
  AppOrdersRoute: typeof AppOrdersRoute
  AppPayablesRoute: typeof AppPayablesRoute
  AppProductionRoute: typeof AppProductionRoute
  AppProductsRoute: typeof AppProductsRoute
  AppReceivablesRoute: typeof AppReceivablesRoute
  AppReportsRoute: typeof AppReportsRoute
  AppSalesRoute: typeof AppSalesRoute
  AppSellersRoute: typeof AppSellersRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSuppliersRoute: typeof AppSuppliersRoute
  AppUsersRoute: typeof AppUsersRoute
  AppWarehousesRoute: typeof AppWarehousesRoute
  AppZonesRoute: typeof AppZonesRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppAuditRoute: AppAuditRoute,
  AppCashboxRoute: AppCashboxRoute,
  AppCustomersRoute: AppCustomersRoute,
  AppInventoryRoute: AppInventoryRoute,
  AppInvoicesRoute: AppInvoicesRoute,
  AppLogisticsRoute: AppLogisticsRoute,
  AppMovementsRoute: AppMovementsRoute,
  AppOrdersRoute: AppOrdersRoute,
  AppPayablesRoute: AppPayablesRoute,
  AppProductionRoute: AppProductionRoute,
  AppProductsRoute: AppProductsRoute,
  AppReceivablesRoute: AppReceivablesRoute,
  AppReportsRoute: AppReportsRoute,
  AppSalesRoute: AppSalesRoute,
  AppSellersRoute: AppSellersRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSuppliersRoute: AppSuppliersRoute,
  AppUsersRoute: AppUsersRoute,
  AppWarehousesRoute: AppWarehousesRoute,
  AppZonesRoute: AppZonesRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  OrderRoute: OrderRoute,
  PortalRoute: PortalRoute,
  SignupRoute: SignupRoute,
  ApiPublicBootstrapAdminRoute: ApiPublicBootstrapAdminRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
