UPDATE public.customers SET neighborhood_id = NULL, zone_id = NULL;
UPDATE public.shipments SET zone_id = NULL;
DELETE FROM public.neighborhoods;
DELETE FROM public.zones;

ALTER TABLE public.neighborhoods ADD COLUMN IF NOT EXISTS priority integer NOT NULL DEFAULT 0;
ALTER TABLE public.neighborhoods DROP CONSTRAINT IF EXISTS neighborhoods_name_key;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'neighborhoods_name_zone_unique') THEN
    ALTER TABLE public.neighborhoods ADD CONSTRAINT neighborhoods_name_zone_unique UNIQUE (name, zone_id);
  END IF;
END $$;
CREATE INDEX IF NOT EXISTS neighborhoods_priority_idx ON public.neighborhoods (priority DESC);

INSERT INTO public.zones (name, priority) VALUES
('Comuna Central', 12),
('Comuna Norte', 12),
('Comuna Occidental', 20),
('Comuna Oriental', 14),
('Comuna Sur Occidental', 20),
('Comuna Sur Oriental', 20);

WITH data(name, zone_name, priority) AS (VALUES
('Acapulco', 'Comuna Occidental', 14),
('Altos de fusa', 'Comuna Sur Oriental', 14),
('Antiguo Balmoral', 'Comuna Occidental', 14),
('Balmoral', 'Comuna Sur Oriental', 14),
('Conjunto La Arboleda', 'Comuna Sur Oriental', 14),
('Conjunto Mirador de la colina', 'Comuna Sur Oriental', 14),
('Conjunto paraiso del balmoral', 'Comuna Sur Oriental', 14),
('El mirador', 'Comuna Sur Oriental', 14),
('El nidito', 'Comuna Occidental', 14),
('El recreo de los alpes', 'Comuna Occidental', 14),
('Fusacatan', 'Comuna Sur Oriental', 14),
('Los robles', 'Comuna Oriental', 14),
('Los Sauces', 'Comuna Sur Oriental', 14),
('Terranova San Jose', 'Comuna Sur Occidental', 14),
('Bosques de Oriente', 'Comuna Sur Oriental', 13),
('Camino real', 'Comuna Sur Oriental', 13),
('Comuneros', 'Comuna Sur Oriental', 13),
('Conjunto Los pinos', 'Comuna Sur Oriental', 13),
('Conjunto Santo domingo', 'Comuna Sur Oriental', 13),
('El vergel', 'Comuna Sur Oriental', 13),
('Macarena', 'Comuna Sur Oriental', 13),
('Las delicias', 'Comuna Sur Oriental', 13),
('Obrero', 'Comuna Sur Oriental', 13),
('Pablo bello', 'Comuna Sur Oriental', 13),
('Pardo Leal', 'Comuna Sur Oriental', 13),
('Prados de Alta gracia', 'Comuna Sur Oriental', 13),
('San fernando', 'Comuna Sur Oriental', 13),
('Santa Barbara', 'Comuna Sur Oriental', 13),
('Urbanización Contigo Con todo', 'Comuna Sur Oriental', 13),
('Urbanización la Macarena', 'Comuna Sur Oriental', 13),
('Urbanización Las americas', 'Comuna Sur Oriental', 13),
('Urbanización Prados de alta gracia', 'Comuna Sur Oriental', 13),
('Urbanización Prados de Betel', 'Comuna Sur Oriental', 13),
('Urbanización Santa Barbara', 'Comuna Sur Oriental', 13),
('Urbanización Santa Rosa', 'Comuna Sur Oriental', 13),
('Villa lady', 'Comuna Sur Oriental', 13),
('Bonet', 'Comuna Oriental', 12),
('Cedritos', 'Comuna Oriental', 12),
('Cementerio', 'Comuna Norte', 12),
('Centro', 'Comuna Central', 12),
('Coburgo', 'Comuna Oriental', 12),
('Comarca española', 'Comuna Occidental', 12),
('Eden', 'Comuna Norte', 12),
('El caribe', 'Comuna Occidental', 12),
('El progreso', 'Comuna Norte', 12),
('Gaitan', 'Comuna Norte', 12),
('Girasoles', 'Comuna Sur Occidental', 12),
('Jose Antonio Galan', 'Comuna Norte', 12),
('La esmeralda', 'Comuna Oriental', 12),
('La esperanza', 'Comuna Norte', 12),
('La florida', 'Comuna Norte', 12),
('La palma', 'Comuna Oriental', 12),
('Mandalay', 'Comuna Occidental', 12),
('Panamericana', 'Comuna Sur Occidental', 12),
('Pekin', 'Comuna Oriental', 12),
('Potosi', 'Comuna Central', 12),
('Santander', 'Comuna Central', 12),
('Villa Aransasu', 'Comuna Oriental', 12),
('Villa Natalia', 'Comuna Norte', 12),
('Antonio Nariño', 'Comuna Oriental', 12),
('Bella vista', 'Comuna Oriental', 12),
('Conjunto la Colina', 'Comuna Sur Oriental', 12),
('El tejar', 'Comuna Oriental', 12),
('Emilio Sierra', 'Comuna Central', 12),
('La abadia de san jorge', 'Comuna Occidental', 12),
('La cabaña', 'Comuna Occidental', 12),
('La cabaña', 'Comuna Norte', 12),
('Las Brisas', 'Comuna Sur Occidental', 12),
('Las eliconias', 'Comuna Sur Occidental', 12),
('Lucero', 'Comuna Oriental', 12),
('Luxemburgo', 'Comuna Central', 12),
('Margaritas', 'Comuna Norte', 12),
('Rincon de valencia', 'Comuna Occidental', 12),
('San Jorge', 'Comuna Occidental', 12),
('Santa maria de los angeles', 'Comuna Oriental', 12),
('Altos de pekin', 'Comuna Oriental', 12),
('Olaya', 'Comuna Central', 12),
('El palmar de manila', 'Comuna Occidental', 11),
('Manila', 'Comuna Occidental', 11),
('Santorini', 'Comuna Occidental', 11),
('Teresita', 'Comuna Occidental', 10),
('Malibu', 'Comuna Occidental', 10),
('Santa Rita', 'Comuna Occidental', 10),
('Villa lorena', 'Comuna Occidental', 10),
('Rincon de capri', 'Comuna Occidental', 9),
('Capri reservado', 'Comuna Occidental', 9),
('La pampa', 'Comuna Sur Occidental', 8),
('Llano alto', 'Comuna Sur Occidental', 8),
('Llano largo', 'Comuna Sur Occidental', 8),
('Llano verde', 'Comuna Sur Occidental', 8),
('Los ocobos', 'Comuna Occidental', 8),
('Maiz Amarillo', 'Comuna Sur Occidental', 8),
('Mirador de San Luis', 'Comuna Sur Occidental', 8),
('Portal de llano largo', 'Comuna Sur Occidental', 8),
('San francisco', 'Comuna Sur Occidental', 8),
('San Luis de Pedregal', 'Comuna Sur Occidental', 8),
('San Marcos', 'Comuna Sur Occidental', 8),
('Altamira', 'Comuna Sur Occidental', 8),
('Villa Celeste', 'Comuna Sur Occidental', 8),
('Villa patricia', 'Comuna Sur Occidental', 8),
('Ebenezer', 'Comuna Sur Occidental', 7),
('Palmeto', 'Comuna Sur Occidental', 6),
('Gran Colombia', 'Comuna Sur Occidental', 6),
('Cambulos', 'Comuna Sur Occidental', 6),
('El portal', 'Comuna Occidental', 6),
('La querencia', 'Comuna Sur Occidental', 5),
('Coviprof', 'Comuna Sur Occidental', 5),
('Tierra grata', 'Comuna Sur Occidental', 4),
('Piedra Grande', 'Comuna Occidental', 4),
('Parque residencial entreverde', 'Comuna Occidental', 4),
('Villa Maria', 'Comuna Sur Occidental', 4),
('La Salle', 'Comuna Sur Occidental', 3),
('San mateo', 'Comuna Occidental', 2),
('Conjunto Bosques de San Luis', 'Comuna Sur Oriental', 2),
('Santa ana reservado', 'Comuna Occidental', 2),
('Marsella', 'Comuna Sur Oriental', 1),
('Bosques de la cañada', 'Comuna Occidental', 1),
('Villa Lenny', 'Comuna Sur Oriental', 1),
('Villas del mediterraneo', 'Comuna Occidental', 1),
('Brisas del quinini', 'Comuna Sur Oriental', 20),
('Conjunto Paseo Real', 'Comuna Sur Occidental', 20),
('Conjunto Santa Catalina', 'Comuna Sur Oriental', 20),
('El nogal', 'Comuna Occidental', 20),
('Fontanar', 'Comuna Occidental', 15),
('La alameda', 'Comuna Occidental', 20),
('La fontana', 'Comuna Occidental', 20),
('Leidy Di', 'Comuna Sur Occidental', 20),
('Maguare', 'Comuna Sur Occidental', 20),
('Nuevo Balmoral', 'Comuna Sur Oriental', 15),
('Santa Anita', 'Comuna Occidental', 15),
('Urbanización Aires del quinini', 'Comuna Sur Oriental', 20),
('Urbanización Akropollo', 'Comuna Sur Oriental', 20),
('Urbanización Florida Blanca', 'Comuna Sur Oriental', 20),
('Urbanización la glorieta', 'Comuna Sur Oriental', 20),
('Urbanización La primavera', 'Comuna Sur Oriental', 20),
('Urbanización las Dellolas', 'Comuna Sur Oriental', 20),
('Urbanización Managua', 'Comuna Sur Oriental', 20),
('Urbanización Parques los Sauces', 'Comuna Sur Oriental', 20),
('Urbanización Toluca', 'Comuna Sur Oriental', 20),
('Villa nice', 'Comuna Occidental', 20)
)
INSERT INTO public.neighborhoods (name, zone_id, priority, active)
SELECT d.name, z.id, d.priority, true FROM data d JOIN public.zones z ON z.name = d.zone_name;